/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv` (hash: 7d92af12876dd9a87c965c1ad499efd4)
interface __BaseEnv_CloudflareEnv {
	ASSETS_BUCKET: R2Bucket;
	BROWSER: BrowserRun;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
