/**
 * Regenerate packages/canvas/src/tailwind-preflight.ts from the installed
 * tailwindcss package (resolves --theme() so the sandbox can use plain CSS).
 *
 *   bun run --cwd packages/canvas embed-preflight
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const version = require('tailwindcss/package.json').version as string
const raw = readFileSync(require.resolve('tailwindcss/preflight.css'), 'utf8')

function resolveThemeFunctions(css: string) {
  return css.replace(
    /--theme\(\s*--[\w-]+\s*,\s*([\s\S]*?)\s*\)/g,
    (_match: string, fallback: string) => fallback.trim(),
  )
}

const resolved = resolveThemeFunctions(raw)
if (resolved.includes('--theme(')) {
  throw new Error('Unresolved --theme() left in preflight CSS')
}

const moduleSource = `/** Generated by scripts/embed-tailwind-preflight.ts — do not edit by hand. */
/** Tailwind CSS ${version} Preflight, with --theme() resolved to fallbacks for sandbox use. */
export const TAILWIND_PREFLIGHT_VERSION = ${JSON.stringify(version)}

export const TAILWIND_PREFLIGHT_CSS = ${JSON.stringify(resolved)}
`

writeFileSync(join(root, 'src/tailwind-preflight.ts'), moduleSource)
console.log(
  `Wrote src/tailwind-preflight.ts (${resolved.length} chars, tailwindcss@${version})`,
)
