/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as McpConsentRouteImport } from './routes/mcp-consent'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known.oauth-authorization-server'
import { Route as ApiCanvasEventsRouteImport } from './routes/api.canvas-events'
import { Route as ApiCanvasPresenceRouteImport } from './routes/api.canvas-presence'
import { Route as ApiReadyRouteImport } from './routes/api.ready'
import { Route as ApiRealtimeTicketRouteImport } from './routes/api.realtime-ticket'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAppearanceRouteImport } from './routes/app.appearance'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppDesignRouteImport } from './routes/app.design'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as DesignIdRouteImport } from './routes/design.$id'
import { Route as ApiAssetIdRouteImport } from './routes/api.asset.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiGithubCallbackRouteImport } from './routes/api.github.callback'
import { Route as ApiGithubConnectRouteImport } from './routes/api.github.connect'
import { Route as ApiGithubInstallRouteImport } from './routes/api.github.install'
import { Route as ApiGithubSetupRouteImport } from './routes/api.github.setup'
import { Route as ApiGithubWebhookRouteImport } from './routes/api.github.webhook'
import { Route as ApiHandoffTokenRouteImport } from './routes/api.handoff.$token'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as DesignIdBBranchIdRouteImport } from './routes/design.$id_.b.$branchId'
import { Route as ApiHandoffTokenAssetIdRouteImport } from './routes/api.handoff.$token.asset.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const McpConsentRoute = McpConsentRouteImport.update({
  id: '/mcp-consent',
  path: '/mcp-consent',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCanvasEventsRoute = ApiCanvasEventsRouteImport.update({
  id: '/api/canvas-events',
  path: '/api/canvas-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanvasPresenceRoute = ApiCanvasPresenceRouteImport.update({
  id: '/api/canvas-presence',
  path: '/api/canvas-presence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: '/api/ready',
  path: '/api/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeTicketRoute = ApiRealtimeTicketRouteImport.update({
  id: '/api/realtime-ticket',
  path: '/api/realtime-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppearanceRoute = AppAppearanceRouteImport.update({
  id: '/app/appearance',
  path: '/app/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/app/billing',
  path: '/app/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDesignRoute = AppDesignRouteImport.update({
  id: '/app/design',
  path: '/app/design',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/app/integrations',
  path: '/app/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIdRoute = DesignIdRouteImport.update({
  id: '/design/$id',
  path: '/design/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetIdRoute = ApiAssetIdRouteImport.update({
  id: '/api/asset/$id',
  path: '/api/asset/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubConnectRoute = ApiGithubConnectRouteImport.update({
  id: '/api/github/connect',
  path: '/api/github/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInstallRoute = ApiGithubInstallRouteImport.update({
  id: '/api/github/install',
  path: '/api/github/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubSetupRoute = ApiGithubSetupRouteImport.update({
  id: '/api/github/setup',
  path: '/api/github/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHandoffTokenRoute = ApiHandoffTokenRouteImport.update({
  id: '/api/handoff/$token',
  path: '/api/handoff/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIdBBranchIdRoute = DesignIdBBranchIdRouteImport.update({
  id: '/design/$id_/b/$branchId',
  path: '/design/$id/b/$branchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHandoffTokenAssetIdRoute = ApiHandoffTokenAssetIdRouteImport.update({
  id: '/asset/$id',
  path: '/asset/$id',
  getParentRoute: () => ApiHandoffTokenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/mcp': typeof McpRoute
  '/mcp-consent': typeof McpConsentRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/api/canvas-events': typeof ApiCanvasEventsRoute
  '/api/canvas-presence': typeof ApiCanvasPresenceRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/realtime-ticket': typeof ApiRealtimeTicketRoute
  '/app/admin': typeof AppAdminRoute
  '/app/appearance': typeof AppAppearanceRoute
  '/app/billing': typeof AppBillingRoute
  '/app/design': typeof AppDesignRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/design/$id': typeof DesignIdRoute
  '/app/': typeof AppIndexRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/handoff/$token': typeof ApiHandoffTokenRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/design/$id/b/$branchId': typeof DesignIdBBranchIdRoute
  '/api/handoff/$token/asset/$id': typeof ApiHandoffTokenAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/mcp': typeof McpRoute
  '/mcp-consent': typeof McpConsentRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/api/canvas-events': typeof ApiCanvasEventsRoute
  '/api/canvas-presence': typeof ApiCanvasPresenceRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/realtime-ticket': typeof ApiRealtimeTicketRoute
  '/app/admin': typeof AppAdminRoute
  '/app/appearance': typeof AppAppearanceRoute
  '/app/billing': typeof AppBillingRoute
  '/app/design': typeof AppDesignRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/design/$id': typeof DesignIdRoute
  '/app': typeof AppIndexRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/handoff/$token': typeof ApiHandoffTokenRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/design/$id/b/$branchId': typeof DesignIdBBranchIdRoute
  '/api/handoff/$token/asset/$id': typeof ApiHandoffTokenAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/mcp': typeof McpRoute
  '/mcp-consent': typeof McpConsentRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/api/canvas-events': typeof ApiCanvasEventsRoute
  '/api/canvas-presence': typeof ApiCanvasPresenceRoute
  '/api/ready': typeof ApiReadyRoute
  '/api/realtime-ticket': typeof ApiRealtimeTicketRoute
  '/app/admin': typeof AppAdminRoute
  '/app/appearance': typeof AppAppearanceRoute
  '/app/billing': typeof AppBillingRoute
  '/app/design': typeof AppDesignRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/design/$id': typeof DesignIdRoute
  '/app/': typeof AppIndexRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/handoff/$token': typeof ApiHandoffTokenRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/design/$id_/b/$branchId': typeof DesignIdBBranchIdRoute
  '/api/handoff/$token/asset/$id': typeof ApiHandoffTokenAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/features'
    | '/mcp'
    | '/mcp-consent'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/.well-known/oauth-authorization-server'
    | '/api/canvas-events'
    | '/api/canvas-presence'
    | '/api/ready'
    | '/api/realtime-ticket'
    | '/app/admin'
    | '/app/appearance'
    | '/app/billing'
    | '/app/design'
    | '/app/integrations'
    | '/design/$id'
    | '/app/'
    | '/api/asset/$id'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/install'
    | '/api/github/setup'
    | '/api/github/webhook'
    | '/api/handoff/$token'
    | '/api/rpc/$'
    | '/design/$id/b/$branchId'
    | '/api/handoff/$token/asset/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/features'
    | '/mcp'
    | '/mcp-consent'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/.well-known/oauth-authorization-server'
    | '/api/canvas-events'
    | '/api/canvas-presence'
    | '/api/ready'
    | '/api/realtime-ticket'
    | '/app/admin'
    | '/app/appearance'
    | '/app/billing'
    | '/app/design'
    | '/app/integrations'
    | '/design/$id'
    | '/app'
    | '/api/asset/$id'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/install'
    | '/api/github/setup'
    | '/api/github/webhook'
    | '/api/handoff/$token'
    | '/api/rpc/$'
    | '/design/$id/b/$branchId'
    | '/api/handoff/$token/asset/$id'
  id:
    | '__root__'
    | '/'
    | '/features'
    | '/mcp'
    | '/mcp-consent'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/.well-known/oauth-authorization-server'
    | '/api/canvas-events'
    | '/api/canvas-presence'
    | '/api/ready'
    | '/api/realtime-ticket'
    | '/app/admin'
    | '/app/appearance'
    | '/app/billing'
    | '/app/design'
    | '/app/integrations'
    | '/design/$id'
    | '/app/'
    | '/api/asset/$id'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/install'
    | '/api/github/setup'
    | '/api/github/webhook'
    | '/api/handoff/$token'
    | '/api/rpc/$'
    | '/design/$id_/b/$branchId'
    | '/api/handoff/$token/asset/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeaturesRoute: typeof FeaturesRoute
  McpRoute: typeof McpRoute
  McpConsentRoute: typeof McpConsentRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  ApiCanvasEventsRoute: typeof ApiCanvasEventsRoute
  ApiCanvasPresenceRoute: typeof ApiCanvasPresenceRoute
  ApiReadyRoute: typeof ApiReadyRoute
  ApiRealtimeTicketRoute: typeof ApiRealtimeTicketRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAppearanceRoute: typeof AppAppearanceRoute
  AppBillingRoute: typeof AppBillingRoute
  AppDesignRoute: typeof AppDesignRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  DesignIdRoute: typeof DesignIdRoute
  AppIndexRoute: typeof AppIndexRoute
  ApiAssetIdRoute: typeof ApiAssetIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
  ApiGithubConnectRoute: typeof ApiGithubConnectRoute
  ApiGithubInstallRoute: typeof ApiGithubInstallRoute
  ApiGithubSetupRoute: typeof ApiGithubSetupRoute
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  ApiHandoffTokenRoute: typeof ApiHandoffTokenRouteWithChildren
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  DesignIdBBranchIdRoute: typeof DesignIdBBranchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-consent': {
      id: '/mcp-consent'
      path: '/mcp-consent'
      fullPath: '/mcp-consent'
      preLoaderRoute: typeof McpConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canvas-events': {
      id: '/api/canvas-events'
      path: '/api/canvas-events'
      fullPath: '/api/canvas-events'
      preLoaderRoute: typeof ApiCanvasEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canvas-presence': {
      id: '/api/canvas-presence'
      path: '/api/canvas-presence'
      fullPath: '/api/canvas-presence'
      preLoaderRoute: typeof ApiCanvasPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ready': {
      id: '/api/ready'
      path: '/api/ready'
      fullPath: '/api/ready'
      preLoaderRoute: typeof ApiReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime-ticket': {
      id: '/api/realtime-ticket'
      path: '/api/realtime-ticket'
      fullPath: '/api/realtime-ticket'
      preLoaderRoute: typeof ApiRealtimeTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/appearance': {
      id: '/app/appearance'
      path: '/app/appearance'
      fullPath: '/app/appearance'
      preLoaderRoute: typeof AppAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/app/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/design': {
      id: '/app/design'
      path: '/app/design'
      fullPath: '/app/design'
      preLoaderRoute: typeof AppDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/app/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$id': {
      id: '/design/$id'
      path: '/design/$id'
      fullPath: '/design/$id'
      preLoaderRoute: typeof DesignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asset/$id': {
      id: '/api/asset/$id'
      path: '/api/asset/$id'
      fullPath: '/api/asset/$id'
      preLoaderRoute: typeof ApiAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/connect': {
      id: '/api/github/connect'
      path: '/api/github/connect'
      fullPath: '/api/github/connect'
      preLoaderRoute: typeof ApiGithubConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/install': {
      id: '/api/github/install'
      path: '/api/github/install'
      fullPath: '/api/github/install'
      preLoaderRoute: typeof ApiGithubInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/setup': {
      id: '/api/github/setup'
      path: '/api/github/setup'
      fullPath: '/api/github/setup'
      preLoaderRoute: typeof ApiGithubSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/handoff/$token': {
      id: '/api/handoff/$token'
      path: '/api/handoff/$token'
      fullPath: '/api/handoff/$token'
      preLoaderRoute: typeof ApiHandoffTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$id_/b/$branchId': {
      id: '/design/$id_/b/$branchId'
      path: '/design/$id/b/$branchId'
      fullPath: '/design/$id/b/$branchId'
      preLoaderRoute: typeof DesignIdBBranchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/handoff/$token/asset/$id': {
      id: '/api/handoff/$token/asset/$id'
      path: '/asset/$id'
      fullPath: '/api/handoff/$token/asset/$id'
      preLoaderRoute: typeof ApiHandoffTokenAssetIdRouteImport
      parentRoute: typeof ApiHandoffTokenRoute
    }
  }
}

interface ApiHandoffTokenRouteChildren {
  ApiHandoffTokenAssetIdRoute: typeof ApiHandoffTokenAssetIdRoute
}

const ApiHandoffTokenRouteChildren: ApiHandoffTokenRouteChildren = {
  ApiHandoffTokenAssetIdRoute: ApiHandoffTokenAssetIdRoute,
}

const ApiHandoffTokenRouteWithChildren = ApiHandoffTokenRoute._addFileChildren(
  ApiHandoffTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeaturesRoute: FeaturesRoute,
  McpRoute: McpRoute,
  McpConsentRoute: McpConsentRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  ApiCanvasEventsRoute: ApiCanvasEventsRoute,
  ApiCanvasPresenceRoute: ApiCanvasPresenceRoute,
  ApiReadyRoute: ApiReadyRoute,
  ApiRealtimeTicketRoute: ApiRealtimeTicketRoute,
  AppAdminRoute: AppAdminRoute,
  AppAppearanceRoute: AppAppearanceRoute,
  AppBillingRoute: AppBillingRoute,
  AppDesignRoute: AppDesignRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  DesignIdRoute: DesignIdRoute,
  AppIndexRoute: AppIndexRoute,
  ApiAssetIdRoute: ApiAssetIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
  ApiGithubConnectRoute: ApiGithubConnectRoute,
  ApiGithubInstallRoute: ApiGithubInstallRoute,
  ApiGithubSetupRoute: ApiGithubSetupRoute,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  ApiHandoffTokenRoute: ApiHandoffTokenRouteWithChildren,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  DesignIdBBranchIdRoute: DesignIdBBranchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
