/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as McpConsentRouteImport } from './routes/mcp-consent'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known.oauth-authorization-server'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppDesignRouteImport } from './routes/app.design'
import { Route as DesignIdRouteImport } from './routes/design.$id'
import { Route as ApiAssetIdRouteImport } from './routes/api.asset.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiFigmaCallbackRouteImport } from './routes/api.figma.callback'
import { Route as ApiFigmaConnectRouteImport } from './routes/api.figma.connect'
import { Route as ApiGithubCallbackRouteImport } from './routes/api.github.callback'
import { Route as ApiGithubConnectRouteImport } from './routes/api.github.connect'
import { Route as ApiGithubInstallRouteImport } from './routes/api.github.install'
import { Route as ApiGithubSetupRouteImport } from './routes/api.github.setup'
import { Route as ApiGithubWebhookRouteImport } from './routes/api.github.webhook'
import { Route as ApiHandoffTokenRouteImport } from './routes/api.handoff.$token'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as DesignIdBBranchIdRouteImport } from './routes/design.$id_.b.$branchId'
import { Route as ApiHandoffTokenAssetIdRouteImport } from './routes/api.handoff.$token.asset.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpConsentRoute = McpConsentRouteImport.update({
  id: '/mcp-consent',
  path: '/mcp-consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDesignRoute = AppDesignRouteImport.update({
  id: '/app/design',
  path: '/app/design',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIdRoute = DesignIdRouteImport.update({
  id: '/design/$id',
  path: '/design/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetIdRoute = ApiAssetIdRouteImport.update({
  id: '/api/asset/$id',
  path: '/api/asset/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFigmaCallbackRoute = ApiFigmaCallbackRouteImport.update({
  id: '/api/figma/callback',
  path: '/api/figma/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFigmaConnectRoute = ApiFigmaConnectRouteImport.update({
  id: '/api/figma/connect',
  path: '/api/figma/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubConnectRoute = ApiGithubConnectRouteImport.update({
  id: '/api/github/connect',
  path: '/api/github/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInstallRoute = ApiGithubInstallRouteImport.update({
  id: '/api/github/install',
  path: '/api/github/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubSetupRoute = ApiGithubSetupRouteImport.update({
  id: '/api/github/setup',
  path: '/api/github/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHandoffTokenRoute = ApiHandoffTokenRouteImport.update({
  id: '/api/handoff/$token',
  path: '/api/handoff/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIdBBranchIdRoute = DesignIdBBranchIdRouteImport.update({
  id: '/design/$id_/b/$branchId',
  path: '/design/$id/b/$branchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHandoffTokenAssetIdRoute = ApiHandoffTokenAssetIdRouteImport.update({
  id: '/asset/$id',
  path: '/asset/$id',
  getParentRoute: () => ApiHandoffTokenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp-consent': typeof McpConsentRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/app/design': typeof AppDesignRoute
  '/design/$id': typeof DesignIdRoute
  '/app/': typeof AppIndexRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/figma/callback': typeof ApiFigmaCallbackRoute
  '/api/figma/connect': typeof ApiFigmaConnectRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/handoff/$token': typeof ApiHandoffTokenRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/design/$id/b/$branchId': typeof DesignIdBBranchIdRoute
  '/api/handoff/$token/asset/$id': typeof ApiHandoffTokenAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp-consent': typeof McpConsentRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/app/design': typeof AppDesignRoute
  '/design/$id': typeof DesignIdRoute
  '/app': typeof AppIndexRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/figma/callback': typeof ApiFigmaCallbackRoute
  '/api/figma/connect': typeof ApiFigmaConnectRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/handoff/$token': typeof ApiHandoffTokenRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/design/$id/b/$branchId': typeof DesignIdBBranchIdRoute
  '/api/handoff/$token/asset/$id': typeof ApiHandoffTokenAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp-consent': typeof McpConsentRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/app/design': typeof AppDesignRoute
  '/design/$id': typeof DesignIdRoute
  '/app/': typeof AppIndexRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/figma/callback': typeof ApiFigmaCallbackRoute
  '/api/figma/connect': typeof ApiFigmaConnectRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/install': typeof ApiGithubInstallRoute
  '/api/github/setup': typeof ApiGithubSetupRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/handoff/$token': typeof ApiHandoffTokenRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/design/$id_/b/$branchId': typeof DesignIdBBranchIdRoute
  '/api/handoff/$token/asset/$id': typeof ApiHandoffTokenAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp-consent'
    | '/.well-known/oauth-authorization-server'
    | '/app/design'
    | '/design/$id'
    | '/app/'
    | '/api/asset/$id'
    | '/api/auth/$'
    | '/api/figma/callback'
    | '/api/figma/connect'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/install'
    | '/api/github/setup'
    | '/api/github/webhook'
    | '/api/handoff/$token'
    | '/api/rpc/$'
    | '/design/$id/b/$branchId'
    | '/api/handoff/$token/asset/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp-consent'
    | '/.well-known/oauth-authorization-server'
    | '/app/design'
    | '/design/$id'
    | '/app'
    | '/api/asset/$id'
    | '/api/auth/$'
    | '/api/figma/callback'
    | '/api/figma/connect'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/install'
    | '/api/github/setup'
    | '/api/github/webhook'
    | '/api/handoff/$token'
    | '/api/rpc/$'
    | '/design/$id/b/$branchId'
    | '/api/handoff/$token/asset/$id'
  id:
    | '__root__'
    | '/'
    | '/mcp-consent'
    | '/.well-known/oauth-authorization-server'
    | '/app/design'
    | '/design/$id'
    | '/app/'
    | '/api/asset/$id'
    | '/api/auth/$'
    | '/api/figma/callback'
    | '/api/figma/connect'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/install'
    | '/api/github/setup'
    | '/api/github/webhook'
    | '/api/handoff/$token'
    | '/api/rpc/$'
    | '/design/$id_/b/$branchId'
    | '/api/handoff/$token/asset/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpConsentRoute: typeof McpConsentRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  AppDesignRoute: typeof AppDesignRoute
  DesignIdRoute: typeof DesignIdRoute
  AppIndexRoute: typeof AppIndexRoute
  ApiAssetIdRoute: typeof ApiAssetIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFigmaCallbackRoute: typeof ApiFigmaCallbackRoute
  ApiFigmaConnectRoute: typeof ApiFigmaConnectRoute
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
  ApiGithubConnectRoute: typeof ApiGithubConnectRoute
  ApiGithubInstallRoute: typeof ApiGithubInstallRoute
  ApiGithubSetupRoute: typeof ApiGithubSetupRoute
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  ApiHandoffTokenRoute: typeof ApiHandoffTokenRouteWithChildren
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  DesignIdBBranchIdRoute: typeof DesignIdBBranchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-consent': {
      id: '/mcp-consent'
      path: '/mcp-consent'
      fullPath: '/mcp-consent'
      preLoaderRoute: typeof McpConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/design': {
      id: '/app/design'
      path: '/app/design'
      fullPath: '/app/design'
      preLoaderRoute: typeof AppDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$id': {
      id: '/design/$id'
      path: '/design/$id'
      fullPath: '/design/$id'
      preLoaderRoute: typeof DesignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asset/$id': {
      id: '/api/asset/$id'
      path: '/api/asset/$id'
      fullPath: '/api/asset/$id'
      preLoaderRoute: typeof ApiAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/figma/callback': {
      id: '/api/figma/callback'
      path: '/api/figma/callback'
      fullPath: '/api/figma/callback'
      preLoaderRoute: typeof ApiFigmaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/figma/connect': {
      id: '/api/figma/connect'
      path: '/api/figma/connect'
      fullPath: '/api/figma/connect'
      preLoaderRoute: typeof ApiFigmaConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/connect': {
      id: '/api/github/connect'
      path: '/api/github/connect'
      fullPath: '/api/github/connect'
      preLoaderRoute: typeof ApiGithubConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/install': {
      id: '/api/github/install'
      path: '/api/github/install'
      fullPath: '/api/github/install'
      preLoaderRoute: typeof ApiGithubInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/setup': {
      id: '/api/github/setup'
      path: '/api/github/setup'
      fullPath: '/api/github/setup'
      preLoaderRoute: typeof ApiGithubSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/handoff/$token': {
      id: '/api/handoff/$token'
      path: '/api/handoff/$token'
      fullPath: '/api/handoff/$token'
      preLoaderRoute: typeof ApiHandoffTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$id_/b/$branchId': {
      id: '/design/$id_/b/$branchId'
      path: '/design/$id/b/$branchId'
      fullPath: '/design/$id/b/$branchId'
      preLoaderRoute: typeof DesignIdBBranchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/handoff/$token/asset/$id': {
      id: '/api/handoff/$token/asset/$id'
      path: '/asset/$id'
      fullPath: '/api/handoff/$token/asset/$id'
      preLoaderRoute: typeof ApiHandoffTokenAssetIdRouteImport
      parentRoute: typeof ApiHandoffTokenRoute
    }
  }
}

interface ApiHandoffTokenRouteChildren {
  ApiHandoffTokenAssetIdRoute: typeof ApiHandoffTokenAssetIdRoute
}

const ApiHandoffTokenRouteChildren: ApiHandoffTokenRouteChildren = {
  ApiHandoffTokenAssetIdRoute: ApiHandoffTokenAssetIdRoute,
}

const ApiHandoffTokenRouteWithChildren = ApiHandoffTokenRoute._addFileChildren(
  ApiHandoffTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpConsentRoute: McpConsentRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  AppDesignRoute: AppDesignRoute,
  DesignIdRoute: DesignIdRoute,
  AppIndexRoute: AppIndexRoute,
  ApiAssetIdRoute: ApiAssetIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFigmaCallbackRoute: ApiFigmaCallbackRoute,
  ApiFigmaConnectRoute: ApiFigmaConnectRoute,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
  ApiGithubConnectRoute: ApiGithubConnectRoute,
  ApiGithubInstallRoute: ApiGithubInstallRoute,
  ApiGithubSetupRoute: ApiGithubSetupRoute,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  ApiHandoffTokenRoute: ApiHandoffTokenRouteWithChildren,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  DesignIdBBranchIdRoute: DesignIdBBranchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
