/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAppearanceRouteImport } from './routes/app.appearance'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppSecurityRouteImport } from './routes/app.security'
import { Route as DesignIdRouteImport } from './routes/design.$id'
import { Route as DesignIdBBranchIdRouteImport } from './routes/design.$id_.b.$branchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppearanceRoute = AppAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const DesignIdRoute = DesignIdRouteImport.update({
  id: '/design/$id',
  path: '/design/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIdBBranchIdRoute = DesignIdBBranchIdRouteImport.update({
  id: '/design/$id_/b/$branchId',
  path: '/design/$id/b/$branchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/appearance': typeof AppAppearanceRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/security': typeof AppSecurityRoute
  '/design/$id': typeof DesignIdRoute
  '/app/': typeof AppIndexRoute
  '/design/$id/b/$branchId': typeof DesignIdBBranchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/appearance': typeof AppAppearanceRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/security': typeof AppSecurityRoute
  '/design/$id': typeof DesignIdRoute
  '/app': typeof AppIndexRoute
  '/design/$id/b/$branchId': typeof DesignIdBBranchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/appearance': typeof AppAppearanceRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/security': typeof AppSecurityRoute
  '/design/$id': typeof DesignIdRoute
  '/app/': typeof AppIndexRoute
  '/design/$id_/b/$branchId': typeof DesignIdBBranchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/appearance'
    | '/app/integrations'
    | '/app/security'
    | '/design/$id'
    | '/app/'
    | '/design/$id/b/$branchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/appearance'
    | '/app/integrations'
    | '/app/security'
    | '/design/$id'
    | '/app'
    | '/design/$id/b/$branchId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/appearance'
    | '/app/integrations'
    | '/app/security'
    | '/design/$id'
    | '/app/'
    | '/design/$id_/b/$branchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DesignIdRoute: typeof DesignIdRoute
  DesignIdBBranchIdRoute: typeof DesignIdBBranchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appearance': {
      id: '/app/appearance'
      path: '/appearance'
      fullPath: '/app/appearance'
      preLoaderRoute: typeof AppAppearanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/security': {
      id: '/app/security'
      path: '/security'
      fullPath: '/app/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/design/$id': {
      id: '/design/$id'
      path: '/design/$id'
      fullPath: '/design/$id'
      preLoaderRoute: typeof DesignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$id_/b/$branchId': {
      id: '/design/$id_/b/$branchId'
      path: '/design/$id/b/$branchId'
      fullPath: '/design/$id/b/$branchId'
      preLoaderRoute: typeof DesignIdBBranchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAppearanceRoute: typeof AppAppearanceRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppearanceRoute: AppAppearanceRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DesignIdRoute: DesignIdRoute,
  DesignIdBBranchIdRoute: DesignIdBBranchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
