/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAppearanceRouteImport } from './routes/app.appearance'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as DesignIdRouteImport } from './routes/design.$id'
import { Route as DesignIdBBranchIdRouteImport } from './routes/design.$id_.b.$branchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppearanceRoute = AppAppearanceRouteImport.update({
  id: '/app/appearance',
  path: '/app/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/app/integrations',
  path: '/app/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIdRoute = DesignIdRouteImport.update({
  id: '/design/$id',
  path: '/design/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIdBBranchIdRoute = DesignIdBBranchIdRouteImport.update({
  id: '/design/$id_/b/$branchId',
  path: '/design/$id/b/$branchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/appearance': typeof AppAppearanceRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/design/$id': typeof DesignIdRoute
  '/app/': typeof AppIndexRoute
  '/design/$id/b/$branchId': typeof DesignIdBBranchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/appearance': typeof AppAppearanceRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/design/$id': typeof DesignIdRoute
  '/app': typeof AppIndexRoute
  '/design/$id/b/$branchId': typeof DesignIdBBranchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/appearance': typeof AppAppearanceRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/design/$id': typeof DesignIdRoute
  '/app/': typeof AppIndexRoute
  '/design/$id_/b/$branchId': typeof DesignIdBBranchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/appearance'
    | '/app/integrations'
    | '/design/$id'
    | '/app/'
    | '/design/$id/b/$branchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/appearance'
    | '/app/integrations'
    | '/design/$id'
    | '/app'
    | '/design/$id/b/$branchId'
  id:
    | '__root__'
    | '/'
    | '/app/appearance'
    | '/app/integrations'
    | '/design/$id'
    | '/app/'
    | '/design/$id_/b/$branchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppAppearanceRoute: typeof AppAppearanceRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  DesignIdRoute: typeof DesignIdRoute
  AppIndexRoute: typeof AppIndexRoute
  DesignIdBBranchIdRoute: typeof DesignIdBBranchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/appearance': {
      id: '/app/appearance'
      path: '/app/appearance'
      fullPath: '/app/appearance'
      preLoaderRoute: typeof AppAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/app/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$id': {
      id: '/design/$id'
      path: '/design/$id'
      fullPath: '/design/$id'
      preLoaderRoute: typeof DesignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$id_/b/$branchId': {
      id: '/design/$id_/b/$branchId'
      path: '/design/$id/b/$branchId'
      fullPath: '/design/$id/b/$branchId'
      preLoaderRoute: typeof DesignIdBBranchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppAppearanceRoute: AppAppearanceRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  DesignIdRoute: DesignIdRoute,
  AppIndexRoute: AppIndexRoute,
  DesignIdBBranchIdRoute: DesignIdBBranchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
