export type CustomDomainDnsRecord = {
  type: 'A' | 'AAAA' | 'CNAME' | 'TXT' | 'CAA' | 'ALIAS' | 'ANAME'
  name: string
  value: string
  required: boolean
}

function withoutTrailingDot(value: string) {
  return value.trim().replace(/\.$/, '')
}

export function providerDnsRecordName(name: string, zone: string) {
  const normalizedName = withoutTrailingDot(name).toLowerCase()
  const normalizedZone = withoutTrailingDot(zone).toLowerCase()
  if (normalizedName === normalizedZone) return '@'
  const suffix = `.${normalizedZone}`
  if (normalizedName.endsWith(suffix)) {
    return normalizedName.slice(0, -suffix.length)
  }
  return normalizedName
}

function zoneRecordValue(record: CustomDomainDnsRecord) {
  if (record.type === 'TXT') {
    const escaped = record.value.replaceAll('\\', '\\\\').replaceAll('"', '\\"')
    return `"${escaped}"`
  }
  if (
    record.type === 'CNAME' ||
    record.type === 'ALIAS' ||
    record.type === 'ANAME'
  ) {
    return `${withoutTrailingDot(record.value)}.`
  }
  return record.value
}

export function dnsRecordsClipboardText(
  records: readonly CustomDomainDnsRecord[],
  zone: string,
) {
  return records
    .filter((record) => record.required)
    .map(
      (record) =>
        `${record.type}  ${providerDnsRecordName(record.name, zone)}  ${record.value}`,
    )
    .join('\n')
}

export function dnsZoneFile(
  records: readonly CustomDomainDnsRecord[],
  zone: string,
) {
  const normalizedZone = withoutTrailingDot(zone).toLowerCase()
  const lines = records
    .filter((record) => record.required)
    .map(
      (record) =>
        `${providerDnsRecordName(record.name, normalizedZone)}\t3600\tIN\t${record.type}\t${zoneRecordValue(record)}`,
    )
  return `; DNS records generated by Loora\n$ORIGIN ${normalizedZone}.\n\n${lines.join('\n')}\n`
}
