#!/usr/bin/env python3
"""Vendor the editor's webfonts into apps/web/public/vendor.

Isolated previews run under a CSP with no outbound network, so a Google Fonts
stylesheet never loads there. Serving the same files from our own origin keeps
those previews offline and makes Canvas use the exact same font bytes.

Run from the repo root: python3 scripts/vendor-fonts.py
"""

import base64
import pathlib
import re
import urllib.request

UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)
CSS_URL = (
    "https://fonts.googleapis.com/css2?"
    "family=Archivo:wght@400;500;600;700&"
    "family=Spline+Sans+Mono:wght@400;500&"
    "family=Inter:wght@400;500;600;700&"
    "family=Space+Grotesk:wght@400;500;600;700&"
    "family=Playfair+Display:wght@400;600;700&"
    "family=Lora:wght@400;500;600&display=swap"
)
SUBSETS = ("latin", "latin-ext")
ROOT = pathlib.Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "apps/web/public/vendor/fonts"
CSS_FILE = ROOT / "apps/web/public/vendor/fonts.css"
SANDBOX_CSS_FILE = ROOT / "apps/web/public/vendor/fonts-sandbox.css"


def fetch(url: str) -> bytes:
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={"User-Agent": UA})
    ).read()


def main() -> None:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in FONT_DIR.glob("*.woff2"):
        stale.unlink()

    css = fetch(CSS_URL).decode()
    # Google emits one @font-face per subset, each preceded by /* subset */.
    blocks = re.findall(r"/\* (\S+) \*/\s*(@font-face \{.*?\})", css, re.S)
    kept = [(subset, block) for subset, block in blocks if subset in SUBSETS]

    header = [
        "/* Generated by scripts/vendor-fonts.py — do not edit by hand.",
        "   Self-hosted so isolated previews render with the same typefaces",
        "   as Canvas. */",
        "",
    ]
    lines = list(header)
    # Element frames are sandboxed without allow-same-origin, so their fetches
    # carry Origin: null. Font files require CORS, which same-origin static
    # assets do not answer — inline them instead of shipping a broken link.
    # Both files must declare identical faces.
    sandbox_lines = list(header)
    seen: set[str] = set()
    count = 0
    for subset, block in kept:
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
        if url in seen:
            continue
        seen.add(url)
        family = re.search(r"font-family: '([^']+)'", block).group(1)
        unicode_range = re.search(r"unicode-range: ([^;]+);", block).group(1)
        # These are variable fonts: one file per family/subset serves every
        # weight, so declare the whole axis instead of Google's per-weight
        # blocks, which would make the browser synthesize bold instead.
        name = f"{family.replace(' ', '-').lower()}-{subset}.woff2"
        data = fetch(url)
        (FONT_DIR / name).write_bytes(data)
        inline = "data:font/woff2;base64," + base64.b64encode(data).decode()

        def face(src: str) -> str:
            return "\n".join([
                f"/* {subset} */",
                "@font-face {",
                f"  font-family: '{family}';",
                "  font-style: normal;",
                "  font-weight: 100 900;",
                "  font-display: swap;",
                f"  src: url({src}) format('woff2');",
                f"  unicode-range: {unicode_range};",
                "}",
                "",
            ])

        lines.append(face(f"/vendor/fonts/{name}"))
        sandbox_lines.append(face(inline))
        count += 1

    CSS_FILE.write_text("\n".join(lines))
    SANDBOX_CSS_FILE.write_text("\n".join(sandbox_lines))
    print(f"{count} faces from {len(kept)} source rules")


if __name__ == "__main__":
    main()
