/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false` (hash: aa3addc9b503b5b4caf314f8af1b12e7)
interface __BaseEnv_Env {
	BETTER_AUTH_URL: string;
	REALTIME_ALLOWED_ORIGINS: string;
	REALTIME_INTERNAL_TOKEN: string;
	REALTIME_TICKET_SECRET: string;
	REALTIME_TICKET_SECRET_PREVIOUS: string;
	REALTIME_ROOMS: DurableObjectNamespace<import("./src/index").RealtimeRoom>;
	REALTIME_USERS: DurableObjectNamespace<import("./src/index").RealtimeUser>;
	REALTIME_INGRESS: DurableObjectNamespace<import("./src/index").RealtimeIngress>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RealtimeRoom" | "RealtimeUser" | "RealtimeIngress";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_URL" | "REALTIME_ALLOWED_ORIGINS" | "REALTIME_INTERNAL_TOKEN" | "REALTIME_TICKET_SECRET" | "REALTIME_TICKET_SECRET_PREVIOUS">> {}
}
