/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiAssetIdRouteImport } from './routes/api.asset.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiHandoffTokenRouteImport } from './routes/api.handoff.$token'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiHandoffTokenAssetIdRouteImport } from './routes/api.handoff.$token.asset.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetIdRoute = ApiAssetIdRouteImport.update({
  id: '/api/asset/$id',
  path: '/api/asset/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHandoffTokenRoute = ApiHandoffTokenRouteImport.update({
  id: '/api/handoff/$token',
  path: '/api/handoff/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHandoffTokenAssetIdRoute = ApiHandoffTokenAssetIdRouteImport.update({
  id: '/asset/$id',
  path: '/asset/$id',
  getParentRoute: () => ApiHandoffTokenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/handoff/$token': typeof ApiHandoffTokenRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/handoff/$token/asset/$id': typeof ApiHandoffTokenAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/handoff/$token': typeof ApiHandoffTokenRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/handoff/$token/asset/$id': typeof ApiHandoffTokenAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/asset/$id': typeof ApiAssetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/handoff/$token': typeof ApiHandoffTokenRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/handoff/$token/asset/$id': typeof ApiHandoffTokenAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/asset/$id'
    | '/api/auth/$'
    | '/api/handoff/$token'
    | '/api/rpc/$'
    | '/api/handoff/$token/asset/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/asset/$id'
    | '/api/auth/$'
    | '/api/handoff/$token'
    | '/api/rpc/$'
    | '/api/handoff/$token/asset/$id'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/asset/$id'
    | '/api/auth/$'
    | '/api/handoff/$token'
    | '/api/rpc/$'
    | '/api/handoff/$token/asset/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiAssetIdRoute: typeof ApiAssetIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiHandoffTokenRoute: typeof ApiHandoffTokenRouteWithChildren
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asset/$id': {
      id: '/api/asset/$id'
      path: '/api/asset/$id'
      fullPath: '/api/asset/$id'
      preLoaderRoute: typeof ApiAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/handoff/$token': {
      id: '/api/handoff/$token'
      path: '/api/handoff/$token'
      fullPath: '/api/handoff/$token'
      preLoaderRoute: typeof ApiHandoffTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/handoff/$token/asset/$id': {
      id: '/api/handoff/$token/asset/$id'
      path: '/asset/$id'
      fullPath: '/api/handoff/$token/asset/$id'
      preLoaderRoute: typeof ApiHandoffTokenAssetIdRouteImport
      parentRoute: typeof ApiHandoffTokenRoute
    }
  }
}

interface ApiHandoffTokenRouteChildren {
  ApiHandoffTokenAssetIdRoute: typeof ApiHandoffTokenAssetIdRoute
}

const ApiHandoffTokenRouteChildren: ApiHandoffTokenRouteChildren = {
  ApiHandoffTokenAssetIdRoute: ApiHandoffTokenAssetIdRoute,
}

const ApiHandoffTokenRouteWithChildren = ApiHandoffTokenRoute._addFileChildren(
  ApiHandoffTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiAssetIdRoute: ApiAssetIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiHandoffTokenRoute: ApiHandoffTokenRouteWithChildren,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
