/**
 * The two things `/desktop/auth` is handed, and the one place it may send an
 * answer.
 *
 * A page that mints a session code from the visitor's own session has to be
 * careful about where that code goes: only to loopback, only to a port the
 * desktop app is listening on, and only when it carries back the state string
 * that app generated. Anything else and the page refuses to connect anything.
 */

export interface DesktopHandoff {
  port: number | null
  state: string | null
}

/** Ports below 1024 need privileges no desktop app has. */
export function parseHandoffPort(value: unknown) {
  const port = Number(value)
  return Number.isInteger(port) && port >= 1024 && port <= 65535 ? port : null
}

/** As generated by the host: 24 random bytes, base64url, so 32 characters. */
export function parseHandoffState(value: unknown) {
  return typeof value === 'string' && /^[A-Za-z0-9_-]{16,64}$/.test(value)
    ? value
    : null
}

export function parseDesktopHandoff(search: Record<string, unknown>): DesktopHandoff {
  return {
    port: parseHandoffPort(search.port),
    state: parseHandoffState(search.state),
  }
}

/** Loopback, always — never a host the query string chose. */
export function desktopCallbackUrl(handoff: {
  port: number
  state: string
  token: string
}) {
  const url = new URL(`http://127.0.0.1:${handoff.port}/callback`)
  url.searchParams.set('token', handoff.token)
  url.searchParams.set('state', handoff.state)
  return url.toString()
}
